services:
  redis:
    image: redis:7-alpine
    container_name: scraper_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: scraper_web
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - pw_sessions:/app/playwright_sessions
      - /dev/shm:/dev/shm
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DISPLAY=host.docker.internal:0.0
      - QT_X11_NO_MITSHM=1
    shm_size: "1gb"
    command: python manage.py runserver 0.0.0.0:8000

  worker:
    build: .
    container_name: scraper_worker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - pw_sessions:/app/playwright_sessions
      - /dev/shm:/dev/shm
    depends_on:
      - redis
    environment:
      - DISPLAY=host.docker.internal:0.0
      - QT_X11_NO_MITSHM=1
    shm_size: "1gb"
    command: ["celery", "-A", "scraper_backend", "worker", "-l", "info", "--concurrency=4"]

  beat:
    build: .
    container_name: scraper_beat
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    command: ["celery", "-A", "scraper_backend", "beat", "-l", "info"]

volumes:
  pw_sessions:
